<?php
require "db.php"; $pageTitle="Department";
$edit_id="";$dept_code="";$dept_name="";$office_location="";$head_of_dept="";$phone="";$email="";
if(isset($_POST['save'])){ $id=(int)$_POST['dept_id']; $code=mysqli_real_escape_string($conn,$_POST['dept_code']); $name=mysqli_real_escape_string($conn,$_POST['dept_name']); $office=mysqli_real_escape_string($conn,$_POST['office_location']); $head=mysqli_real_escape_string($conn,$_POST['head_of_dept']); $ph=mysqli_real_escape_string($conn,$_POST['phone']); $em=mysqli_real_escape_string($conn,$_POST['email']); if($id>0){$sql="UPDATE department SET dept_code='$code',dept_name='$name',office_location='$office',head_of_dept='$head',phone='$ph',email='$em' WHERE dept_id=$id";}else{$sql="INSERT INTO department(dept_code,dept_name,office_location,head_of_dept,phone,email) VALUES('$code','$name','$office','$head','$ph','$em')";} if(mysqli_query($conn,$sql)){header("Location: department.php?message=Department saved successfully");exit;} $error=mysqli_error($conn);}
if(isset($_POST['delete'])){$id=(int)$_POST['delete_id'];if(mysqli_query($conn,"DELETE FROM department WHERE dept_id=$id")){header("Location: department.php?message=Department deleted successfully");exit;} $error=mysqli_error($conn);}
if(isset($_GET['edit'])){$edit_id=(int)$_GET['edit'];$r=mysqli_fetch_assoc(mysqli_query($conn,"SELECT * FROM department WHERE dept_id=$edit_id"));if($r){$dept_code=$r['dept_code'];$dept_name=$r['dept_name'];$office_location=$r['office_location'];$head_of_dept=$r['head_of_dept'];$phone=$r['phone'];$email=$r['email'];}}
require "header.php";
if(isset($error))echo '<div class="message error">'.htmlspecialchars($error).'</div>';
?>
<h1>Department Form</h1><div class="card"><form action="department.php" method="POST"><input type="hidden" name="dept_id" value="<?php echo $edit_id;?>"><div class="form-grid">
<div class="field"><label>Department Code</label><input name="dept_code" value="<?php echo htmlspecialchars($dept_code);?>" required></div><div class="field"><label>Department Name</label><input name="dept_name" value="<?php echo htmlspecialchars($dept_name);?>" required></div><div class="field"><label>Office Location</label><input name="office_location" value="<?php echo htmlspecialchars($office_location);?>" required></div><div class="field"><label>Head of Department</label><input name="head_of_dept" value="<?php echo htmlspecialchars($head_of_dept);?>" required></div><div class="field"><label>Phone</label><input name="phone" value="<?php echo htmlspecialchars($phone);?>" required></div><div class="field"><label>Email</label><input type="email" name="email" value="<?php echo htmlspecialchars($email);?>" required></div></div><div class="actions"><button class="btn" name="save" type="submit"><?php echo $edit_id?'Update Department':'Save Department';?></button><a class="btn secondary" href="department.php">Clear</a></div></form></div>
<div class="card"><h2>Department Records</h2><div class="table-wrap"><table><tr><th>dept_id</th><th>Code</th><th>Name</th><th>Office</th><th>Head</th><th>Phone</th><th>Email</th><th>Actions</th></tr><?php $q=mysqli_query($conn,"SELECT * FROM department ORDER BY dept_id DESC");while($r=mysqli_fetch_assoc($q)){echo '<tr><td>'.$r['dept_id'].'</td><td>'.htmlspecialchars($r['dept_code']).'</td><td>'.htmlspecialchars($r['dept_name']).'</td><td>'.htmlspecialchars($r['office_location']).'</td><td>'.htmlspecialchars($r['head_of_dept']).'</td><td>'.htmlspecialchars($r['phone']).'</td><td>'.htmlspecialchars($r['email']).'</td><td><a class="btn" href="department.php?edit='.$r['dept_id'].'">Edit</a> <form action="department.php" method="POST" style="display:inline"><input type="hidden" name="delete_id" value="'.$r['dept_id'].'"><button class="btn danger" name="delete" onclick="return confirm(\'Delete?\')">Delete</button></form></td></tr>';}?></table></div></div><?php require "footer.php";?>
